[general]
name = "mpfr-fix"
version = "0.6.0"
fix_version = "1.5.0"
description = "MPFR bindings for the Fix programming language."

[build]
files = ["mpfr.fix"]
dynamic_links = ["mpfr", "gmp"]

[build.test]
files = ["mpfr-test.fix"]
memcheck = true


[[dependencies]]
name = "gmp-fix"
version = "0.9.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-gmp.git", rev = "002065bd9884066715f26858b79d787ef14cf380" }
